### ISSUE TITLE
generate "\**\*" style path in windows system

### ISSUE THREAD

**Issue by richardyou** [whxaxes/egg-ts-helper#1]
https://github.com/whxaxes/egg-ts-helper/blob/8c4c770a27fc846e13f7af3e49ddfc0814f72760/src/generators/class.ts#L44

import Home from '..\..\..\app\controller\home';
if it contains sub controller,it will generate 
```
import Home from '..\..\..\app\controller\home';
import Posts from '..\..\..\app\controller\posts';
import Sub/index from '..\..\..\app\controller\sub\index';

declare module 'egg' {
  interface IController {
    home: Home;
    posts: Posts;
    sub/index: Sub/index;
  }
}
```
which is a syntax error.
Can egg-ts-helper support ```-linux``` argument?

**Comment by whxaxes** [comment]
OK，I would fixed it today

**Comment by whxaxes** [comment]
upgrade to `0.1.2` would fixed this bug
