### ISSUE TITLE
编译时不训练别tsconfig.json中的paths配置

### ISSUE THREAD

**Issue by shipfi** [whxaxes/egg-ts-helper#12]
tsconfig.json中配置如下：
```javascript
{
     compilerOptions : {
          "baseUrl": ".",
          "paths": {
               "@/*": [ "app/*" ]
          },
    }
}
```

然后我在代码中引用模块使用的方式为：
```javascript
import {ErrCode} from "@/library/common/errcode";
```

编译时报错：
[egg-core] load file: E:\SourceCode\QinggerSource\MicroService\ali-express-sms-service\app\controller\baseController.ts, error: Cannot find module '@/library/common/errcode'

**Comment by whxaxes** [comment]
这个跟 egg-ts-helper 没关系，也跟 egg ts 没关系，就算你用 tsc 也一样

**Comment by whxaxes** [comment]
本身 ts 编译成 js 就是不会去转换连接的

**Comment by whxaxes** [comment]
如果你要处理，可以考虑用一下 https://github.com/dividab/tsconfig-paths

**Comment by shipfi** [comment]
收到，谢谢。

**Comment by taosher** [comment]
> 如果你要处理，可以考虑用一下 https://github.com/dividab/tsconfig-paths

compile的时候不转链接没问题的，和tsc行为一致。

但是egg-bin dev的时候应该支持的吧？毕竟ts-ndoe本身就是支持的。现在这种egg-bin的封装，在走到ts-ndoe前就报错了，几乎相当于tsconfig的paths配置不可用了...

**Comment by whxaxes** [comment]
@taosher 只是 dev 支持，那你跑线上不得挂了 .... 问题不是更严重了？

**Comment by whxaxes** [comment]
@taosher  还有就是。。。你哪里看到 ts-node 支持的？什么叫走到 ts-node 前就报错，不经过 ts-node ts 怎么变 js ？怎么跑得起来？

**Comment by taosher** [comment]
> @taosher 还有就是。。。你哪里看到 ts-node 支持的？什么叫走到 ts-node 前就报错，不经过 ts-node ts 怎么变 js ？怎么跑得起来？

额，我搞错了...我之前的项目是用了tsconfig-paths的...
