### ISSUE TITLE
在register里面追加 silent 选项

### ISSUE THREAD

**Issue by iwege** [whxaxes/egg-ts-helper#16]
## 场景
在 test 的时候 created 的log往往会截断测试用例的信息，并且没有办法设置[silent](https://github.com/whxaxes/egg-ts-helper/blob/master/src/bin.ts#L60)

## 期望
能否在[register](https://github.com/whxaxes/egg-ts-helper/blob/master/src/register.ts#L36) 增加相关的配置开关，过滤掉相关的log

**Comment by whxaxes** [comment]
在 test 的时候确实不需要打印日志，`1.13.0` 已经在 test 的时候关闭日志了
