### ISSUE TITLE
 [Egg 兼容] caseStyle 参数支持函数入参

### ISSUE THREAD

**Issue by plusmancn** [whxaxes/egg-ts-helper#18]
场景是这样的：
我们内部封装的插件内使用到了 Egg 的 `FileLoader`，其中 `caseStyle` 参数传入的是一个 `function` 用于自定义挂载的节点名。
翻阅 `egg-ts-helper` 的源码，发现并不支持函数传入。

不知是否有支持的考虑，可以提 PR

**Comment by whxaxes** [comment]
可以，欢迎 PR

**Comment by plusmancn** [comment]
@whxaxes 已提交

**Comment by whxaxes** [comment]
1.14.0
