### ISSUE TITLE
1.19.0 建议升级大版本，历史项目如果定义了 interfaceHandle 会挂。

### ISSUE THREAD

**Issue by plusmancn** [whxaxes/egg-ts-helper#24]
RT

**Comment by whxaxes** [comment]
不会吧？错误给我看看？

**Comment by whxaxes** [comment]
这个版本没有 break change，如果出现问题，那就是 bug ，我修复一下即可

**Comment by plusmancn** [comment]
![image](https://user-images.githubusercontent.com/4994682/49867867-b3a68280-fe46-11e8-83a5-b2d136f60caf.png)

**Comment by whxaxes** [comment]
嗯，这个确实是我的疏忽了，我想想怎么来处理好

**Comment by whxaxes** [comment]
用户定义了 interfaceHandle 的情况下应该不在外面再盖一层的，我待会发个 patch 修复一下

**Comment by whxaxes** [comment]
fixed in 1.19.1
