### ISSUE TITLE
js egg project中自动生成index.d.ts的问题

### ISSUE THREAD

**Issue by tulies** [whxaxes/egg-ts-helper#28]
## 自动生成的代码是这样的
```js
// This file is created by egg-ts-helper
// Do not modify this file!!!!!!!!!

import 'egg';
import ExportHome = require('../../../app/controller/home');

declare module 'egg' {
  interface IController {
    home: ExportHome;
  }
}

```

`import ExportHome = require('../../../app/controller/home');` 这个感觉好怪啊。。 是不是应该用`import ExportHome from '../../../app/controller/home';`

**Comment by whxaxes** [comment]
因为你的项目是 js 项目，而 js 项目的模块都是 commonjs 的，对于 commonjs 的模块就是用 `import xxx = require('xxx')` 方式的，可以看一下 https://www.typescriptlang.org/docs/handbook/modules.html

如果是 ts 项目就是 esm 的方式

**Comment by tulies** [comment]
@whxaxes 明白了。。 谢谢
