### ISSUE TITLE
对egg model的支持

### ISSUE THREAD

**Issue by qinshou** [whxaxes/egg-ts-helper#3]
诸如Sequelize、Mongoose等框架会使用 `app/model` 目录，建议开放对其他目录监听的支持

就算不做自动添加`d.ts`当做监听编译也好，现在egg typescript下，sequelize是完全不可用的

**Comment by atzcl** [comment]
在 `egg ts` 下，`sequelize`、`mongoose` 是可以正常使用的，建议查看下对应的 `@types` 包的 `.d.ts` 写法

**Comment by whxaxes** [comment]
这个不属于 egg-ts-helper 的工作范畴了，model 是 egg-sequelize 提供的能力，应该由插件去提供支持

**Comment by whxaxes** [comment]
目前 egg-ts-helper 本来就没有去处理 model 目录，因为 model 的能力是 egg-sequelize 这个插件提供的，如果有需要解析 model 的话，欢迎提 PR

**Comment by whxaxes** [comment]
嗯，也有道理，我会放进开发计划中，之后会加上 model 的支持

**Comment by Maroon1** [comment]
由于 egg 的 loader 机制，要想结合 TS 使用 egg，了解类型定义方法是不得不迈过去的一个坎，不可能什么样的类型都要插件自动生成，其他的插件需要的 model 也有可能不一致，在文档中详细说明各种场景下的类型声明技巧才是根本。
