### ISSUE TITLE
egg-mysql如何支持？

### ISSUE THREAD

**Issue by zhump** [whxaxes/egg-ts-helper#34]
https://eggjs.org/zh-cn/tutorials/mysql.html

这个插件是否不支持提示，在源码里也没有找到可使用的基类。
```
this.app.mysql.xxx
```

**Comment by whxaxes** [comment]
https://github.com/eggjs/egg-mysql 暂时没有定义声明文件，欢迎 PR 补充。如果急着用，在项目的声明里加一下 

```typescript
declare module 'egg' {
  interface Application {
    mysql: any;
  }
}
```

临时解决
