### ISSUE TITLE
process.on('uncaughtException', clean) should throw the error

### ISSUE THREAD

**Issue by skyitachi** [whxaxes/egg-ts-helper#35]
when code has some global error, eg: require('noneexist') , egg-ts-helper would swallow the error, make the egg-bin dev just halt. I think it should throw error

**Comment by whxaxes** [comment]
It's a bug, I will fix it today, thanks

**Comment by whxaxes** [comment]
https://github.com/whxaxes/egg-ts-helper/pull/36
