### ISSUE TITLE
1.23.0 to 1.25.2, auto build diff

### ISSUE THREAD

**Issue by webignorant** [whxaxes/egg-ts-helper#47]
// This file is created by egg-ts-helper@1.25.2
// Do not modify this file!!!!!!!!!

老版本不含版本号，所以不同机器与环境下这里的comment都是一致的。
新版本发现带上版本号，导致使用新老版本的开发者之间一直提示代码差异

**Comment by whxaxes** [comment]
这种自动生成的声明，就不应该提交到代码仓库
