### ISSUE TITLE
helper 的实际调试端口与指定的端口不一致

### ISSUE THREAD

**Issue by Maroon1** [whxaxes/egg-ts-helper#5]
如下指定 `portNumber` 时，实际调试时需要 attach 的端口为 `portNumber + 1`

```bash
egg-bin debug --inspect=<portNumber> -r egg-ts-helper/register
```

**Comment by whxaxes** [comment]
这个跟 egg-ts-helper 没关系吧？

**Comment by Maroon1** [comment]
我是使用 VSCode 的 Debug 工具，目前调试的时候遇到2个问题：
1. 没法很直观的知道所要 Attach 的调试端口号，经测试是 inspect 的端口号 +1
2. 每次进程重启后端口号都会变掉，每次都要再次手动 Attach

我不知道这个是 node 的问题还是，开发工具的问题，但是和 nodemon 一起使用时是可以自动 Attach 的

**Comment by whxaxes** [comment]
@Maroon1  https://eggjs.org/zh-cn/core/development.html#%E4%BD%BF%E7%94%A8-vscode-%E8%BF%9B%E8%A1%8C%E8%B0%83%E8%AF%95   看这个

**Comment by Maroon1** [comment]
谢了，之前安装错插件了，哈哈
