### ISSUE TITLE
1.25.6生成的mode/index.d.ts 与之前的有差异，导致编译不过

### ISSUE THREAD

**Issue by pc1995** [whxaxes/egg-ts-helper#52]
![image](https://user-images.githubusercontent.com/19453215/63735632-0af46200-c8b3-11e9-9eec-a79d3d5ed6b2.png)
```js
  const article = await ctx.model.Article.findById(id); // 这里找不到Article
```

![image](https://user-images.githubusercontent.com/19453215/63735660-1d6e9b80-c8b3-11e9-8bfc-a65e5d8d1c6a.png)

**Comment by whxaxes** [comment]
升级一下 egg-sequelize 就可以了，原来的实现很容易有坑，是属于临时方案，所以改成统一走 IModel 了。或者你手动在 package.json 里加一下这个配置就可以了

```json
{
  "name": "app",
  "egg": {
    "tsHelper": {
      "watchDirs.model.framework": "sequelize",
      "watchDirs.model.interface": "Sequelize"
    }
  }
}
```

再或者就升级一下 egg-sequelize ，基本上是平滑升级（ 只需要把 findById 改成 findByPK 即可，示例：https://github.com/eggjs/examples/tree/master/sequelize-ts  ）

**Comment by pc1995** [comment]
> 升级一下 egg-sequelize 就可以了，原来的实现很容易有坑，是属于临时方案，所以改成统一走 IModel 了。或者你手动在 package.json 里加一下这个配置就可以了
> 
> ```json
> {
>   "name": "app",
>   "egg": {
>     "tsHelper": {
>       "watchDirs.model.framework": "sequelize",
>       "watchDirs.model.interface": "Sequelize"
>     }
>   }
> }
> ```
> 
> 再或者就升级一下 egg-sequelize ，基本上是平滑升级（ 只需要把 findById 改成 findByPK 即可，示例：https://github.com/eggjs/examples/tree/master/sequelize-ts ）

感谢感谢，已经解决了，谢谢啦
