### ISSUE TITLE
Auto generated typing errors

### ISSUE THREAD

**Issue by hsuehic** [whxaxes/egg-ts-helper#54]
![image](https://user-images.githubusercontent.com/7324648/68557976-8c02d480-0472-11ea-90b2-ae7f99dce9b6.png)
![image](https://user-images.githubusercontent.com/7324648/68558076-f3b91f80-0472-11ea-9f8f-ed2ab7ebc7ce.png)

**Comment by whxaxes** [comment]
给个可复现的 repo

**Comment by hsuehic** [comment]
sorry, 是egg-socket.io 里的一个类型定义问题。
