### ISSUE TITLE
webstorm

### ISSUE THREAD

**Issue by duncup** [whxaxes/egg-ts-helper#55]
我试了下这个，发现在 webstorm 中始终无法跳转到 service 下的方法上。在 vs code 里是可用的。想请教下是我姿势不对还是确实和 webstrom 的提示不兼容。

**Comment by whxaxes** [comment]
这个跟 egg-ts-helper 无关，跟 egg 里的声明有关，egg 的声明方式（ `declare module 'egg'`  ）在 webstorm 下识别似乎有 bug ，目前还没找到解法

**Comment by duncup** [comment]
3q

**Comment by zhangciwu** [comment]
我的解决方法：添加一个app/index.d.ts，内容如下

```typescript
import {BaseContextClass, Context, IService} from 'egg';
import 'egg'; // Make sure ts to import egg declaration at first


declare module 'egg' {
  export interface Context {
    service: IService;
  }


  export interface IService {
  }


  export class BaseContextClass {
    public ctx: Context;
  }
}
```

这样webstorm就可以识别出来了

**Comment by whxaxes** [comment]
@duncup  有空的话，帮忙验证一下上面那种做法？我这边没有 webstorm 的 license 了 ...
