### ISSUE TITLE
在midway中使用时，plugin.d.ts只会生成内置插件但声明，外部插件的声明不会自动生成

### ISSUE THREAD

**Issue by grtan** [whxaxes/egg-ts-helper#63]
![image](https://user-images.githubusercontent.com/11453989/82302720-92a77100-99ec-11ea-9d12-4a3007a282fe.png)

![image](https://user-images.githubusercontent.com/11453989/82302747-9c30d900-99ec-11ea-851b-b265d010e597.png)

**Comment by whxaxes** [comment]
midway 的目录结构跟 egg 的不太一样，使用 midway 的话就用依赖注入吧，不需要用 egg 这套自动生成的方案了

**Comment by grtan** [comment]
使用的外部插件会自动挂载到app上啊，这时候没有提示

![image](https://user-images.githubusercontent.com/11453989/82303620-c3d47100-99ed-11ea-9c70-60d6a17dab3e.png)
