### ISSUE TITLE
egg-ts-helper/register 生成 d.ts 是自己 watch 了文件变更吗

### ISSUE THREAD

**Issue by tudou527** [whxaxes/egg-ts-helper#7]
从 egg-watcher 的源码：https://github.com/eggjs/egg-watcher/blob/master/lib/watcher.js#L31 看，可以通过  `agent.watcher.watch('{filePath}', (file) => {});` watch 文件变更，想问一下为什么 register 没用这种方式？因为我们也有一个类似的功能需要在文件变更时做一些其他的事情

**Comment by whxaxes** [comment]
因为 egg-ts-helper 需要在应用启动前就生成好 d.ts ，如果没有生成 d.ts 就直接跑应用很可能 ts 解析就跪了，而如果使用 egg 的 watcher，就必须做成 egg 插件集成进去，那么就得启动应用了，这个先后次序就有问题了
