### ISSUE TITLE
circulate type

### ISSUE THREAD

**Issue by allfornaruto** [whxaxes/egg-ts-helper#70]
![image](https://user-images.githubusercontent.com/32056555/104469258-4f40e900-55f3-11eb-8bed-a68e688d903e.png)
![image](https://user-images.githubusercontent.com/32056555/104469333-5e279b80-55f3-11eb-980d-fcbdebdb9f0c.png)
遇到循环引用咋办哦？

**Comment by whxaxes** [comment]
可以考虑把 skipLibCheck 改成 true

**Comment by whxaxes** [comment]
不过看你这个写法，理论上不会有这个问题，可以刷新一下 tsc 缓存再看看
