### ISSUE TITLE
egg-mongoose自动生成该如何配置呢？

### ISSUE THREAD

**Issue by Micjoyce** [whxaxes/egg-ts-helper#8]

**Comment by whxaxes** [comment]
egg-mongoose 组件里的声明中的 `MongooseModels` 的类型是一个 type，而不是一个 interface ，而 interface 和 type 是没法做声明合并的，所以 egg-ts-helper 没法往这个 `MongooseModels` 挂载方法，解决方案是：

1. 提个 PR ，把 `egg-mongoose` 中的 `MongooseModels` 改成 interface。
2. 然后在项目下加个 `tshelper.js`，然后 js 中添加以下这段代码即可自动生成

```js
module.exports = {
  watchDirs: {
    model: {
      framework: 'egg',
      interface: 'MongooseModels',
      trigger: ['add', 'unlink'],
    }
  }
}
```

目前生成的 typings 是会有问题的，因为 MongooseModels 是 type

**Comment by whxaxes** [comment]
还有一个办法，将 egg-ts-helper 升到 1.10.0 ，然后将 typescript 控制在 2.x 版本，在 typings/index.d.ts 中添加这么一个声明

```typescript
import { MongooseModels } from 'egg';

declare module 'egg' {
  interface IModel extends MongooseModels {}

  // extend app
  interface Application {
    model: IModel;
  }

  // extend context
  interface Context {
    model: IModel;
  }
}
```

但是 ts3.0 不行，因为 `Application.model` 这个槽位被 egg-mongoose 占了，而 ts3.0 不允许复写 model 的类型

**Comment by Micjoyce** [comment]
我本来是通过在tshelper.js禁用

```
watchDirs: {
    model: false
  }
```
然后手动写model,你这个方法已经非常OK
非常谢谢
